### ISSUE TITLE
It would be nice if you could provide one file after the merge

### ISSUE THREAD

**Issue by skyformat99** [anrieff/cxxptl#1]
In addition, merge all the files into a single header file

**Comment by anrieff** [comment]
Sorry, I don't understand your request. What do you mean by "merge"? You want a single-header library?

**Comment by skyformat99** [comment]
thanks.
Similar to the amalgamation version code  provided by SQLite.
A header file  +   a cpp  file,  so it's easy to use.

**Comment by anrieff** [comment]
Hmm, I'm not familiar with those. But I can write a script that collects all code into a single .h file, if that works for you.

**Comment by skyformat99** [comment]
Thanks, That's pretty good.

**Comment by anrieff** [comment]
Fixed in f795483.
